import { ArrowDownRight, ArrowUpRight, Mail, MapPin, Menu, MessageCircle } from 'lucide-react';
import { content } from '../site.config';
const processes = [['01','Cultivated','Grown by trusted smallholder partners across the cool, volcanic highlands surrounding Bandung.'],['02','Processed','Careful cherry selection and considered natural, washed, and honey processes reveal each lot’s character.'],['03','Prepared','Graded, cupped, and prepared for export with dependable documentation and lot traceability.']];
const qualities = [['Specialty grade','Selected lots scoring 80+ with clear provenance and a clean, expressive cup.'],['Natural character','Sweet, fruit-led profiles shaped by the soil, elevation, and patient processing.'],['Responsible supply','Long-term farmer relationships support fairer value and resilient harvests.'],['Export ready','Consistent preparation, secure packaging, and practical support from sample to shipment.']];

export default function Home() { return <main>
  <header className="site-header"><a className="brand" href="#top"><span>Palapa</span> Coffee</a><nav className="desktop-nav"><a href="#origin">Coffee Origin</a><a href="#quality">Coffee Quality</a><a href="#about">About Us</a><a className="contact-button" href="#contact">Contact Us <ArrowUpRight size={16}/></a></nav><details className="mobile-nav"><summary><Menu/></summary><div><a href="#origin">Origin</a><a href="#quality">Quality</a><a href="#about">About</a><a href="#contact">Contact</a></div></details></header>
  <section id="top" className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(26,20,13,.82),rgba(26,20,13,.18)),url(${content.images.hero})`}}><div className="eyebrow light"><span/> From Java · To the world</div><h1>Bandung coffee,<br/><em>beautifully</em> expressed.</h1><p>Green coffee rooted in the Sunda highlands, selected with care and prepared for roasters around the world.</p><div className="hero-actions"><a href="#origin">Discover our origin <ArrowDownRight size={17}/></a><span>West Java, Indonesia<br/>6.9° S · 107.6° E</span></div></section>
  <section id="origin" className="section origin"><div className="section-heading"><div><div className="eyebrow"><span/> Coffee origin</div><h2>Originated from<br/>the Land of Sunda.</h2></div><p>Our coffee begins in the green folds of Bandung’s volcanic highlands. Cool air, generous rainfall, and mineral-rich soils let cherries mature slowly, building the sweetness and lively character that distinguish West Java in every cup.</p></div><div className="origin-image" style={{backgroundImage:`linear-gradient(rgba(24,38,25,.46),rgba(24,38,25,.46)),url(${content.images.gallery[0]})`}}><span>1,200–1,700 MASL</span><strong>Bandung Highlands</strong></div><div className="process-grid">{processes.map((x,i)=><article key={x[1]}><img src={content.images.process[i]} alt="Coffee production in West Java"/><div className="card-number">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="gallery-strip">{content.images.gallery.map((src,i)=><img key={src} src={src} alt={`Palapa Coffee origin story ${i+1}`}/>)}</div></section>
  <section id="quality" className="section quality"><div className="quality-intro"><img src={content.images.quality} alt="Coffee cherries being carefully selected"/><div><div className="eyebrow light"><span/> Coffee quality</div><h2>Our oath is to give sustainable and natural coffee to the world.</h2><p>Quality starts long before a sample reaches the cupping table. We work close to origin, following every lot from cherry selection through processing and final preparation. That care creates green coffee with dependable physical quality, clear flavor, and a story buyers can stand behind.</p><p>Our approach is practical and personal: listen to growers, protect the character of each harvest, and give importers and roasters the information they need to buy with confidence.</p><a href="#contact">Request our current offer list <ArrowUpRight size={17}/></a></div></div><div className="quality-grid">{qualities.map((x,i)=><article key={x[0]}><img src={content.images.qualityCards[i]} alt={x[0]}/><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
  <section id="about" className="section about"><div className="about-pictures left"><img src={content.images.about[0]} alt="Coffee farmer in Bandung"/><img src={content.images.about[1]} alt="Coffee cherries on the tree"/></div><div className="about-copy"><div className="eyebrow"><span/> About Palapa</div><h2>Who we are?</h2><p>Palapa Coffee was founded from a simple conviction: remarkable Java coffee deserves a clear path to the world. Based in Bandung, we connect the work of West Java’s growers and processors with importers, independent roasters, and coffee shops who care about origin.</p><p>We are an export partner with our feet at origin. That means fewer layers, honest communication, and attention to the details that matter, from samples and specifications to preparation and shipment.</p><blockquote>“We want every relationship to feel as considered as the coffee itself.”</blockquote><div className="signature">Founder, Palapa Coffee<br/><span>Bandung · Indonesia</span></div></div><div className="about-pictures right"><img src={content.images.about[2]} alt="Coffee landscape"/><img src={content.images.about[3]} alt="Coffee cupping"/></div></section>
  <section id="contact" className="contact"><div className="contact-title"><div><div className="eyebrow light"><span/> Let’s talk coffee</div><h2>Bring the taste of Java<br/><em>to your market.</em></h2></div><p>Tell us what you are looking for. We welcome sample requests, sourcing conversations, and long-term partnerships.</p></div><div className="contact-grid"><a href={content.links.whatsapp} target="_blank" rel="noreferrer"><MessageCircle/><span>WhatsApp</span><strong>Start a conversation</strong><ArrowUpRight className="corner"/></a><a href={`mailto:${content.links.email}`}><Mail/><span>Email</span><strong>{content.links.email}</strong><ArrowUpRight className="corner"/></a><div><MapPin/><span>Our base</span><strong>{content.address}</strong></div></div></section>
  <footer><a className="brand" href="#top"><span>Palapa</span> Coffee</a><p>Green coffee from Bandung, Indonesia.</p><div><a href={content.links.whatsapp}>WhatsApp</a><a href={`mailto:${content.links.email}`}>Email</a><a href={content.links.instagram}>Instagram</a></div><small>© 2026 Palapa Coffee</small></footer>
</main> }
